version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile.dev
    command: npm run start:web:dev
    volumes:
      - .:/oopsiee

  job-processor:
    build:
      dockerfile: Dockerfile.dev
    command: npm run start:job-processor:dev
    volumes:
      - .:/oopsiee
