version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    expose:
      - ${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    depends_on:
      - redis
    networks:
      - oopsiee

  job-processor:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - oopsiee

  redis:
    image: bitnami/redis:latest
    expose:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - oopsiee

networks:
  oopsiee:
    driver: bridge
