version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile.prod
    command: npm run start:web:prod

  job-processor:
    build:
      dockerfile: Dockerfile.prod
    command: npm run start:job-processor:prod
